version: '3'
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: dragon-nacos-standalone
    networks:
      - dragon-net
    env_file:
      - ../env/nacos.env
    volumes:
      - ../data/nacos-server/logs/:/home/nacos/logs
      - ../config/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555
    restart: on-failure

networks:
  dragon-net:
    external: true