version: '3'
services:
  redis:
    image: redis:alpine
    container_name: dragon-redis
    restart: always
    volumes:
      - ../data/redis:/data
    networks:
      - dragon-net
    ports:
      - 6379:6379
    env_file:
      - ../env/redis.env

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: dragon-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - dragon-net
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ../env/rabbitmq.env

  mysql:
    image: mysql:5.7
    container_name: dragon-mysql
    restart: always
    networks:
      - dragon-net
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    env_file:
      - ../env/mysql.env

networks:
  dragon-net:
    external: true